CREATE TABLE EMP_BACKUP (
    EMP_NAME VARCHAR(100) NOT NULL,
    EMP_ID INT PRIMARY KEY,
    DESIGNATION VARCHAR(50),
    GENDER CHAR(1),
    MOB_NO VARCHAR(15),
    EMAIL VARCHAR(100),
    PSWD VARCHAR(100)
);

DELIMITER //

CREATE TRIGGER TRIG_EMP
BEFORE DELETE ON EMPLOYEE
FOR EACH ROW
BEGIN
    INSERT INTO EMP_BACKUP
    (EMP_NAME, EMP_ID, DESIGNATION, GENDER, MOB_NO, EMAIL, PSWD)
    VALUES
    (OLD.EMP_NAME, OLD.EMP_ID, OLD.DESIGNATION, OLD.GENDER, OLD.MOB_NO, OLD.EMAIL, OLD.PSWD);
END//

DELIMITER ;